# Generated by Django 5.2 on 2025-05-07 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('listingID', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('sqrMeters', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnailPath', models.CharField(max_length=255)),
                ('postDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('typeID', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Postcodes',
            fields=[
                ('postcode', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='listing.listings')),
                ('imagePath', models.CharField(max_length=255)),
            ],
        ),
    ]
