# Generated by Django 5.2 on 2025-05-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagePath', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('sqrMeters', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnailPath', models.CharField(max_length=255)),
                ('postDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Postcodes',
            fields=[
                ('postcode', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
