# Generated by Django 5.2 on 2025-05-12 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.ImageField(default='/static/img/default.jpg', max_length=255, upload_to='img/listingimages/')),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('sqr_meters', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail_path', models.ImageField(upload_to='img/listingimages/')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Postcodes',
            fields=[
                ('postcode', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
