# Generated by Django 5.2 on 2025-05-08 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='sellerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.sellerprofile'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='listingID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listing.listings'),
        ),
        migrations.AddField(
            model_name='listings',
            name='typeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listingtype'),
        ),
        migrations.AddField(
            model_name='listings',
            name='postcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.postcodes'),
        ),
    ]
