# Generated by Django 5.2 on 2025-05-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='type_id',
            new_name='type',
        ),
        migrations.AddField(
            model_name='listings',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listings',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
