# Generated by Django 5.2 on 2025-05-12 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0003_rename_buyer_id_offers_buyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('method', models.CharField(choices=[('creditcard', 'Credit Card'), ('transfer', 'Bank Transfer'), ('loan', 'Loan')], default='creditcard', max_length=20)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.offers')),
            ],
        ),
    ]
