# Generated by Django 5.2 on 2025-05-07 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offerID', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('postDate', models.DateTimeField()),
                ('expiryDate', models.DateTimeField()),
                ('status', models.TextField()),
                ('buyerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listings')),
            ],
        ),
    ]
