# Generated by Django 5.2 on 2025-05-08 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('postDate', models.DateTimeField()),
                ('expiryDate', models.DateTimeField()),
                ('status', models.TextField()),
                ('buyerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listings')),
            ],
        ),
    ]
