# Generated by Django 5.2 on 2025-05-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='listing_id',
            new_name='listing',
        ),
    ]
