# Generated by Django 5.2 on 2025-05-07 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('personalID', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('profileImagePath', models.CharField(max_length=255)),
                ('coverImagePath', models.CharField(max_length=255)),
                ('registerDate', models.DateTimeField()),
                ('postcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.postcodes')),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.users')),
                ('logoPath', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('isCompany', models.BooleanField()),
            ],
        ),
    ]
