# Generated by Django 5.2 on 2025-05-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
