# Generated by Django 5.2 on 2025-05-15 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_rename_listing_id_listingimage_listing_and_more'),
        ('user', '0002_rename_user_id_sellerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cover_image_path',
            field=models.ImageField(default='img/coverimages/default.jpg', upload_to='img/coverimages/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_image_path',
            field=models.ImageField(default='img/profilepics/default.jpg', upload_to='img/profilepics/'),
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
